### ISSUE TITLE
Hook up auto email responder

### ISSUE THREAD

**Issue by melodyma** [imagine-x/website#6]
Anthony has chosen email provider. Anthony will do.

**Comment by TsuiAnthonYVR** [comment]
Hooked up to Mailchimp, caveat is that they don't do welcome mails unless we pay. So I've hooked up the double-opt-in email to send like a welcome email for now.

It is possible to send via Mandrill, which has a 2000 email limit.  That will be a good problem to have.

Please try signing up for now with a newish email address on imagine-x.ca to see how it looks.
